apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:julielee-dev/argocd-deploy.git'
    targetRevision: HEAD
    path: 'charts/hello-world'
    helm:
      values: |
        replicaCount: 1
        image:
          tag: dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
